# ---
# deployment:
#   tasks:
#     - export DEPLOYPATH=/home/qt504q5qgm0e/app.medicy.in/
#     - /qt504q5qgm0e/bin/cp * $DEPLOYPATH



---
deployment:
  tasks:
    - export DEPLOYPATH=/home/qt504q5qgm0e/app.medicy.in/
    - /usr/local/cpanel/3rdparty/bin/git pull origin main -f
